version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - "postgres"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'

  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - '6379:6379'

  commands_service:
    build: .
    container_name: commands_service
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'

volumes:
  postgres-data: {}
  app-storage: {}
networks:
  default:
